// MQL5 code is now generated by the AI pipeline (netlify/functions/parse-strategy.mts).
// This module provides export filename helpers and a validation report builder.
// It no longer contains hardcoded EMA generation logic.

import type { StrategyBlueprint } from "@/types/blueprint";

export function buildExportFilename(blueprint: StrategyBlueprint, ext: string): string {
  const base = (blueprint.name || "strategy")
    .replace(/[^\w-]+/g, "_")
    .replace(/_+/g, "_")
    .replace(/^_|_$/g, "");
  return `${base}.${ext}`;
}

export function buildValidationReport(blueprint: StrategyBlueprint): string {
  const checks: string[] = [];
  const r = blueprint.risk;
  const e = blueprint.execution;

  checks.push(
    r.riskPercent <= 2
      ? `[OK]   Risk per trade: ${r.riskPercent}% (within recommended ≤ 2%)`
      : `[WARN] Risk per trade: ${r.riskPercent}% — consider reducing below 2%`,
  );

  checks.push(
    r.rewardRisk >= 1.5
      ? `[OK]   Reward:risk: 1:${r.rewardRisk}`
      : `[WARN] Reward:risk: 1:${r.rewardRisk} — below recommended 1:1.5`,
  );

  checks.push(
    e.spreadFilterPoints > 0
      ? `[OK]   Spread guard: ${e.spreadFilterPoints} points`
      : `[WARN] No spread guard — vulnerable to wide-spread entries`,
  );

  checks.push(
    blueprint.rules.length > 0
      ? `[OK]   ${blueprint.rules.length} rule(s) extracted from prompt`
      : `[WARN] No rules extracted — re-describe your strategy in more detail`,
  );

  const buyRules = blueprint.rules.filter((r) => r.side === "buy" || r.side === "both");
  const sellRules = blueprint.rules.filter((r) => r.side === "sell" || r.side === "both");
  checks.push(
    buyRules.length > 0
      ? `[OK]   ${buyRules.length} buy-side rule(s)`
      : `[WARN] No buy rules — EA will not open long positions`,
  );
  checks.push(
    sellRules.length > 0
      ? `[OK]   ${sellRules.length} sell-side rule(s)`
      : `[WARN] No sell rules — EA will not open short positions`,
  );

  if (blueprint.subjectiveRuleIds.length > 0) {
    checks.push(
      `[WARN] ${blueprint.subjectiveRuleIds.length} rule(s) flagged as subjective — answer pending clarifications`,
    );
  }

  const compilablePct =
    blueprint.rules.length > 0
      ? Math.round((blueprint.compilableRuleIds.length / blueprint.rules.length) * 100)
      : 0;
  checks.push(`[INFO] Compilability: ${compilablePct}% of rules are machine-codeable`);
  checks.push(`[INFO] AI confidence: ${blueprint.confidence}%`);

  const lines = [
    `Validation report: ${blueprint.name}`,
    `Symbol: ${e.symbol}  |  Setup TF: ${e.setupTimeframe}  |  Entry TF: ${e.entryTimeframe}`,
    `Strategy type: ${blueprint.strategyType.join(", ") || "unknown"}`,
    `─────────────────────────────────────────────────`,
    ...checks,
  ];

  if (blueprint.pendingClarifications.length > 0) {
    lines.push(``, `Pending clarifications:`);
    blueprint.pendingClarifications.forEach((q, i) => {
      lines.push(`  ${i + 1}. ${q}`);
    });
  }

  lines.push(``, `Disclaimer: This validation does not assess profitability.`);
  lines.push(`MQL5 code is AI-generated — always test on a demo account first.`);

  return lines.join("\n");
}

export function buildMockCompileLog(blueprint: StrategyBlueprint): string {
  return [
    `MetaEditor compile log (placeholder)`,
    `──────────────────────────────────────`,
    `File:    ${buildExportFilename(blueprint, "mq5")}`,
    `Result:  0 errors, 0 warnings`,
    `Note:    Compile this file in MetaEditor 5 to verify real compilation.`,
    `         The AI generates syntactically correct MQL5 but cannot run MetaEditor.`,
  ].join("\n");
}
