// ─── MTF Orchestrator Generator ──────────────────────────────────────────────
// Generates MQL5 Expert Advisor source for a multi-timeframe strategy.
//
// Architecture:
//   Phase 1 (Detector) → Phase 2 (State Module) → MTF Orchestrator → Execution
//
// The orchestrator reads indicator buffers from Phase 2 State Modules via
// iCustom() — one handle per step, each on its configured timeframe.
// Steps are evaluated in declaration order; step N becomes ACTIVE only after
// step N-1 is CONFIRMED.  If a step expires before confirming, the chain
// resets to WAITING from that step.

import type { MtfOrchestratorConfig } from "./mtf-types";

export { MTF_ORCHESTRATOR_VERSION } from "./mtf-types";

// ─── Generator ───────────────────────────────────────────────────────────────

export function generateMtfOrchestrator(cfg: MtfOrchestratorConfig): string {
  const { name, direction, steps, execution: e } = cfg;
  const n      = steps.length;
  const isBull = direction === "BULL";
  const dir    = isBull ? "BUY" : "SELL";
  const order  = isBull ? "ORDER_TYPE_BUY" : "ORDER_TYPE_SELL";

  if (n < 2 || n > 6) {
    throw new Error(`MTF orchestrator requires 2–6 steps, got ${n}`);
  }

  const L: string[] = [];
  const ln = (...s: string[]) => L.push(...s);

  // ── Header ─────────────────────────────────────────────────────────────────
  ln(
    `//+------------------------------------------------------------------+`,
    `//| ${name}.mq5`,
    `//| Phase 3 — MTF Strategy Orchestrator  (${n} steps · ${dir})`,
    `//| Generated by EAbuilder2`,
    `//+------------------------------------------------------------------+`,
    `#property copyright "EAbuilder2"`,
    `#property version   "1.00"`,
    `#property strict`,
    ``,
    `#include <Trade\\Trade.mqh>`,
    `#include <Trade\\PositionInfo.mqh>`,
    ``,
  );

  // ── Step status constants ──────────────────────────────────────────────────
  ln(
    `//─── Step status codes ────────────────────────────────────────────────────────`,
    `#define STEP_WAITING    0    // awaiting prior step — dependency not yet CONFIRMED`,
    `#define STEP_ACTIVE     1    // dependency satisfied — monitoring for own signal`,
    `#define STEP_CONFIRMED  2    // signal received — acts as dependency for next step`,
    `#define STEP_EXPIRED    3    // timed out — chain resets from this step`,
    ``,
    `#define STEP_COUNT      ${n}`,
    ``,
  );

  // ── Step inputs ────────────────────────────────────────────────────────────
  for (let i = 0; i < n; i++) {
    const s = steps[i];
    const p = `InpS${i + 1}`;
    ln(
      `//─── Step ${i + 1}: ${s.label} ────────────────────────────────────────────────────────`,
      `input group "══════════ Step ${i + 1}: ${s.label} ══════════"`,
      `input string          ${p}Module    = "${s.moduleName}";  // Module file name (no .mq5)`,
      `input ENUM_TIMEFRAMES ${p}TF        = ${s.timeframe};`,
      `input int             ${p}Lookback  = ${s.lookback};                  // Bars of history for this module`,
      `input int             ${p}BufIdx    = ${s.bufIdx};                    // Signal buffer index (0=BullConfirm 1=BearConfirm)`,
      `input double          ${p}Trigger   = ${s.triggerValue.toFixed(1)};                  // Buffer value that confirms this step`,
      `input int             ${p}Expiry    = ${s.expiryBars};                   // Exec-TF bars before chain resets`,
      ``,
    );
  }

  // ── Execution inputs ───────────────────────────────────────────────────────
  ln(
    `//─── Execution ────────────────────────────────────────────────────────────────`,
    `input group "══════════ Execution ══════════"`,
    `input int             InpMagic        = ${e.magic};             // EA Magic Number`,
    `input int             InpSlippage     = ${e.slippage};                    // Max slippage (points)`,
    `input double          InpRiskPct      = ${e.riskPct.toFixed(1)};                  // Risk per trade (% of balance)`,
    `input double          InpRR           = ${e.rr.toFixed(1)};                  // Reward-to-risk ratio for TP`,
    `input double          InpBreakevenR   = ${e.breakevenR.toFixed(1)};                  // Move SL to BE at N×R profit (0 = off)`,
    `input int             InpMaxTrades    = ${e.maxTrades};                    // Max concurrent positions`,
    `input int             InpMaxSpreadPts = ${e.maxSpreadPts};                   // Max spread before signal blocked`,
    ``,
    `//─── SL source`,
    `// The FINAL step's module must expose an SL price buffer.`,
    `// FVG_State_Module standard: 2 = BullSLBuf, 3 = BearSLBuf`,
    `input group "══════════ SL Source ══════════"`,
    `input int             InpExecSLBufIdx = ${e.slBufIdx};                    // SL buffer index in final step module`,
    ``,
  );

  // ── Runtime globals ────────────────────────────────────────────────────────
  ln(
    `//─── Runtime state ────────────────────────────────────────────────────────────`,
    `int      gStatus[STEP_COUNT];       // per-step STEP_* status`,
    `int      gBarsAlive[STEP_COUNT];    // bars elapsed while ACTIVE`,
    `int      gHandle[STEP_COUNT];       // iCustom handles`,
    `datetime gConfirmedAt[STEP_COUNT];  // bar time when each step confirmed`,
    ``,
    `// Step config arrays — populated in OnInit from inputs`,
    `string          gMods[STEP_COUNT];`,
    `ENUM_TIMEFRAMES gTFs[STEP_COUNT];`,
    `int             gBufs[STEP_COUNT];`,
    `double          gTrigs[STEP_COUNT];`,
    `int             gExpiries[STEP_COUNT];`,
    ``,
    `CTrade        trade;`,
    `CPositionInfo posInfo;`,
    `datetime      gLastBarTime = 0;`,
    ``,
  );

  // ── OnInit ─────────────────────────────────────────────────────────────────
  ln(
    `//─── OnInit ───────────────────────────────────────────────────────────────────`,
    `int OnInit() {`,
    `   trade.SetExpertMagicNumber(InpMagic);`,
    `   trade.SetDeviationInPoints(InpSlippage);`,
    ``,
    `   //--- Populate config arrays from inputs`,
  );
  for (let i = 0; i < n; i++) {
    const p = `InpS${i + 1}`;
    ln(
      `   gMods[${i}]     = ${p}Module;  gTFs[${i}]   = ${p}TF;  gBufs[${i}]     = ${p}BufIdx;`,
      `   gTrigs[${i}]    = ${p}Trigger; gExpiries[${i}] = ${p}Expiry;`,
    );
  }
  ln(
    ``,
    `   //--- Load iCustom handles`,
    `   // Each module receives (tf, lookback) as its first two inputs.`,
    `   // Display / colour inputs use the module's compiled defaults.`,
  );
  for (let i = 0; i < n; i++) {
    const p = `InpS${i + 1}`;
    ln(
      `   gHandle[${i}] = iCustom(_Symbol, gTFs[${i}], gMods[${i}], ${p}TF, ${p}Lookback);`,
    );
  }
  ln(
    ``,
    `   for(int i = 0; i < STEP_COUNT; i++) {`,
    `      if(gHandle[i] == INVALID_HANDLE) {`,
    `         PrintFormat("[MTF_ORC] INIT_FAILED  step=%d  module=%s  tf=%s — check Indicators folder",`,
    `            i + 1, gMods[i], EnumToString(gTFs[i]));`,
    `         return INIT_FAILED;`,
    `      }`,
    `   }`,
    ``,
    `   ArrayInitialize(gStatus,    STEP_WAITING);`,
    `   ArrayInitialize(gBarsAlive, 0);`,
    ``,
    `   PrintFormat("[MTF_ORC] ${name} ready | steps=%d  dir=${dir}  magic=%d", STEP_COUNT, InpMagic);`,
    `   return INIT_SUCCEEDED;`,
    `}`,
    ``,
  );

  // ── OnDeinit ───────────────────────────────────────────────────────────────
  ln(
    `//─── OnDeinit ─────────────────────────────────────────────────────────────────`,
    `void OnDeinit(const int reason) {`,
    `   for(int i = 0; i < STEP_COUNT; i++) {`,
    `      if(gHandle[i] != INVALID_HANDLE) IndicatorRelease(gHandle[i]);`,
    `   }`,
    `}`,
    ``,
  );

  // ── OnTick ─────────────────────────────────────────────────────────────────
  ln(
    `//─── OnTick ───────────────────────────────────────────────────────────────────`,
    `void OnTick() {`,
    `   if(InpBreakevenR > 0.0) ManageBreakeven();`,
    ``,
    `   // One chain-update per closed bar`,
    `   datetime barT = iTime(_Symbol, PERIOD_CURRENT, 0);`,
    `   if(barT == gLastBarTime) return;`,
    `   gLastBarTime = barT;`,
    ``,
    `   UpdateChain();`,
    `}`,
    ``,
  );

  // ── UpdateChain ────────────────────────────────────────────────────────────
  ln(
    `//─── UpdateChain — evaluate each step in dependency order ────────────────────`,
    `void UpdateChain() {`,
    `   for(int i = 0; i < STEP_COUNT; i++) {`,
    ``,
    `      //--- Already confirmed — skip`,
    `      if(gStatus[i] == STEP_CONFIRMED) continue;`,
    ``,
    `      //--- Dependency: step i requires step (i-1) to be CONFIRMED`,
    `      if(i > 0 && gStatus[i - 1] != STEP_CONFIRMED) {`,
    `         if(gStatus[i] != STEP_WAITING) {`,
    `            gStatus[i]    = STEP_WAITING;`,
    `            gBarsAlive[i] = 0;`,
    `         }`,
    `         continue;`,
    `      }`,
    ``,
    `      //--- Activate this step (first bar after dependency confirmed)`,
    `      if(gStatus[i] == STEP_WAITING) {`,
    `         gStatus[i]    = STEP_ACTIVE;`,
    `         gBarsAlive[i] = 0;`,
    `         PrintFormat("[MTF_ORC] STEP_%d_ACTIVE  module=%s  tf=%s",`,
    `            i + 1, gMods[i], EnumToString(gTFs[i]));`,
    `      }`,
    ``,
    `      //--- Expiry check`,
    `      gBarsAlive[i]++;`,
    `      if(gBarsAlive[i] > gExpiries[i]) {`,
    `         PrintFormat("[MTF_ORC] STEP_%d_EXPIRED  bars=%d  chain reset from step %d",`,
    `            i + 1, gBarsAlive[i], i + 1);`,
    `         ResetFrom(i);`,
    `         return;  // re-evaluate on next bar`,
    `      }`,
    ``,
    `      //--- Read signal buffer (bar index 1 = last fully closed bar)`,
    `      double buf[1];`,
    `      if(CopyBuffer(gHandle[i], gBufs[i], 1, 1, buf) < 1) continue;`,
    ``,
    `      if(buf[0] == gTrigs[i]) {`,
    `         gStatus[i]      = STEP_CONFIRMED;`,
    `         gConfirmedAt[i] = iTime(_Symbol, gTFs[i], 1);`,
    `         PrintFormat("[MTF_ORC] STEP_%d_CONFIRMED  module=%s  tf=%s  at=%s",`,
    `            i + 1, gMods[i], EnumToString(gTFs[i]), TimeToString(gConfirmedAt[i]));`,
    `      }`,
    `   }`,
    ``,
    `   //--- Check if every step is confirmed`,
    `   for(int i = 0; i < STEP_COUNT; i++) {`,
    `      if(gStatus[i] != STEP_CONFIRMED) return;`,
    `   }`,
    ``,
    `   Print("[MTF_ORC] ALL_STEPS_CONFIRMED — executing ${dir}");`,
    `   TriggerExecution();`,
    `   ResetAll();`,
    `}`,
    ``,
  );

  // ── Reset helpers ──────────────────────────────────────────────────────────
  ln(
    `//─── ResetFrom / ResetAll ─────────────────────────────────────────────────────`,
    `void ResetFrom(int fromIdx) {`,
    `   for(int i = fromIdx; i < STEP_COUNT; i++) {`,
    `      gStatus[i]    = STEP_WAITING;`,
    `      gBarsAlive[i] = 0;`,
    `   }`,
    `}`,
    `void ResetAll() { ResetFrom(0); }`,
    ``,
  );

  // ── TriggerExecution ───────────────────────────────────────────────────────
  ln(
    `//─── TriggerExecution ─────────────────────────────────────────────────────────`,
    `void TriggerExecution() {`,
    `   //--- Read SL from the final step's module`,
    `   double slBuf[1];`,
    `   if(CopyBuffer(gHandle[STEP_COUNT - 1], InpExecSLBufIdx, 1, 1, slBuf) < 1) {`,
    `      Print("[MTF_ORC] SIGNAL_BLOCKED  reason=sl_buffer_read_failed");`,
    `      return;`,
    `   }`,
    `   if(slBuf[0] <= 0.0) {`,
    `      Print("[MTF_ORC] SIGNAL_BLOCKED  reason=sl_zero");`,
    `      return;`,
    `   }`,
    ``,
    `   //--- Spread filter`,
    `   int spread = (int)SymbolInfoInteger(_Symbol, SYMBOL_SPREAD);`,
    `   if(spread > InpMaxSpreadPts) {`,
    `      PrintFormat("[MTF_ORC] SIGNAL_BLOCKED  reason=spread  val=%d  max=%d", spread, InpMaxSpreadPts);`,
    `      return;`,
    `   }`,
    ``,
    `   //--- Max trades filter`,
    `   int openCount = CountPositions();`,
    `   if(openCount >= InpMaxTrades) {`,
    `      PrintFormat("[MTF_ORC] SIGNAL_BLOCKED  reason=max_trades  open=%d  max=%d", openCount, InpMaxTrades);`,
    `      return;`,
    `   }`,
    ``,
    `   OpenTrade(${order}, slBuf[0]);`,
    `}`,
    ``,
  );

  // ── OpenTrade ──────────────────────────────────────────────────────────────
  ln(
    `//─── OpenTrade ────────────────────────────────────────────────────────────────`,
    `void OpenTrade(ENUM_ORDER_TYPE type, double sl) {`,
    `   double entry = (type == ORDER_TYPE_BUY)`,
    `                  ? SymbolInfoDouble(_Symbol, SYMBOL_ASK)`,
    `                  : SymbolInfoDouble(_Symbol, SYMBOL_BID);`,
    `   double slDist = MathAbs(entry - sl);`,
    ``,
    `   if(slDist <= 0.0) {`,
    `      PrintFormat("[MTF_ORC] SIGNAL_BLOCKED  reason=sl_invalid  entry=%.5f  sl=%.5f", entry, sl);`,
    `      return;`,
    `   }`,
    `   double minStop = (double)SymbolInfoInteger(_Symbol, SYMBOL_TRADE_STOPS_LEVEL) * _Point;`,
    `   if(slDist < minStop) {`,
    `      PrintFormat("[MTF_ORC] SIGNAL_BLOCKED  reason=sl_too_close  slDist=%.5f  minStop=%.5f", slDist, minStop);`,
    `      return;`,
    `   }`,
    `   if(type == ORDER_TYPE_BUY  && sl >= entry) {`,
    `      Print("[MTF_ORC] SIGNAL_BLOCKED  reason=sl_above_entry");  return;`,
    `   }`,
    `   if(type == ORDER_TYPE_SELL && sl <= entry) {`,
    `      Print("[MTF_ORC] SIGNAL_BLOCKED  reason=sl_below_entry");  return;`,
    `   }`,
    ``,
    `   double tp   = (type == ORDER_TYPE_BUY) ? entry + slDist * InpRR`,
    `                                           : entry - slDist * InpRR;`,
    `   double lots = CalcLots(slDist);`,
    `   if(lots <= 0.0) { Print("[MTF_ORC] SIGNAL_BLOCKED  reason=zero_lots"); return; }`,
    ``,
    `   bool ok = (type == ORDER_TYPE_BUY)`,
    `             ? trade.Buy (lots, _Symbol, entry, sl, tp)`,
    `             : trade.Sell(lots, _Symbol, entry, sl, tp);`,
    ``,
    `   string dirStr = (type == ORDER_TYPE_BUY) ? "BUY" : "SELL";`,
    `   if(ok) {`,
    `      PrintFormat("[MTF_ORC] TRADE_OPENED  dir=%s  entry=%.5f  sl=%.5f  tp=%.5f  lots=%.2f  risk=%.1f%%",`,
    `         dirStr, entry, sl, tp, lots, InpRiskPct);`,
    `   } else {`,
    `      PrintFormat("[MTF_ORC] TRADE_FAILED  dir=%s  retcode=%d  entry=%.5f  sl=%.5f",`,
    `         dirStr, (int)trade.ResultRetcode(), entry, sl);`,
    `   }`,
    `}`,
    ``,
  );

  // ── CalcLots ───────────────────────────────────────────────────────────────
  ln(
    `//─── CalcLots — risk-based position sizing ────────────────────────────────────`,
    `double CalcLots(double slDist) {`,
    `   double balance    = AccountInfoDouble(ACCOUNT_BALANCE);`,
    `   double tickVal    = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_VALUE);`,
    `   double tickSz     = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_SIZE);`,
    `   double lotStep    = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_STEP);`,
    `   double minLot     = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MIN);`,
    `   double maxLot     = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MAX);`,
    `   if(tickVal <= 0.0 || tickSz <= 0.0 || slDist <= 0.0) return 0.0;`,
    `   double riskAmt    = balance * InpRiskPct / 100.0;`,
    `   double valPerUnit = tickVal / tickSz;`,
    `   double lots       = riskAmt / (slDist * valPerUnit);`,
    `   lots = MathFloor(lots / lotStep) * lotStep;`,
    `   return MathMax(minLot, MathMin(maxLot, lots));`,
    `}`,
    ``,
  );

  // ── ManageBreakeven ────────────────────────────────────────────────────────
  ln(
    `//─── ManageBreakeven — runs every tick ────────────────────────────────────────`,
    `void ManageBreakeven() {`,
    `   if(InpBreakevenR <= 0.0) return;`,
    `   for(int i = PositionsTotal() - 1; i >= 0; i--) {`,
    `      if(!posInfo.SelectByIndex(i)) continue;`,
    `      if(posInfo.Magic() != InpMagic || posInfo.Symbol() != _Symbol) continue;`,
    ``,
    `      double openPrice = posInfo.PriceOpen();`,
    `      double curSL     = posInfo.StopLoss();`,
    `      double curTP     = posInfo.TakeProfit();`,
    ``,
    `      // Skip if SL already at or beyond entry`,
    `      if(posInfo.PositionType() == POSITION_TYPE_BUY  && curSL >= openPrice) continue;`,
    `      if(posInfo.PositionType() == POSITION_TYPE_SELL && curSL <= openPrice) continue;`,
    ``,
    `      double slDist  = MathAbs(openPrice - curSL);`,
    `      double lotVal  = posInfo.Volume()`,
    `                       * SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_VALUE)`,
    `                       / SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_SIZE);`,
    `      double rValue  = slDist * lotVal;`,
    ``,
    `      if(posInfo.Profit() >= InpBreakevenR * rValue) {`,
    `         if(trade.PositionModify(posInfo.Ticket(), openPrice, curTP)) {`,
    `            PrintFormat("[MTF_ORC] BREAKEVEN_SET  ticket=%d  entry=%.5f  profit=%.2f",`,
    `               (int)posInfo.Ticket(), openPrice, posInfo.Profit());`,
    `         }`,
    `      }`,
    `   }`,
    `}`,
    ``,
  );

  // ── CountPositions ─────────────────────────────────────────────────────────
  ln(
    `//─── CountPositions ───────────────────────────────────────────────────────────`,
    `int CountPositions() {`,
    `   int count = 0;`,
    `   for(int i = PositionsTotal() - 1; i >= 0; i--) {`,
    `      if(!posInfo.SelectByIndex(i)) continue;`,
    `      if(posInfo.Magic() == InpMagic && posInfo.Symbol() == _Symbol) count++;`,
    `   }`,
    `   return count;`,
    `}`,
    `//+------------------------------------------------------------------+`,
  );

  return L.join("\n");
}

// ─── Example strategy configurations ─────────────────────────────────────────

// ── FVG 3-Timeframe Bull  (D1 → H4 → M30 → BUY) ─────────────────────────────
export const FVG_3TF_BULL: MtfOrchestratorConfig = {
  id:          "fvg-3tf-bull",
  name:        "MTF_FVG_3TF_Bull",
  description:
    "D1 FVG bull confirm → H4 FVG bull confirm → M30 FVG entry signal → BUY. " +
    "Classic top-down confluence: daily bias, H4 setup, M30 entry trigger. " +
    "Requires FVG_State_Module.mq5 compiled in MQL5/Indicators/.",
  direction: "BULL",
  steps: [
    {
      label:        "D1 FVG Bull Confirm",
      moduleName:   "FVG_State_Module",
      timeframe:    "PERIOD_D1",
      lookback:     200,
      bufIdx:       0,   // BullConfirmBuf
      triggerValue: 1.0,
      expiryBars:   10,
    },
    {
      label:        "H4 FVG Bull Confirm",
      moduleName:   "FVG_State_Module",
      timeframe:    "PERIOD_H4",
      lookback:     300,
      bufIdx:       0,
      triggerValue: 1.0,
      expiryBars:   24,
    },
    {
      label:        "M30 FVG Entry Signal",
      moduleName:   "FVG_State_Module",
      timeframe:    "PERIOD_M30",
      lookback:     500,
      bufIdx:       0,
      triggerValue: 1.0,
      expiryBars:   40,
    },
  ],
  execution: {
    slBufIdx:     2,   // BullSLBuf
    magic:        20250601,
    riskPct:      1.0,
    rr:           2.0,
    breakevenR:   0.5,
    maxTrades:    1,
    maxSpreadPts: 20,
    slippage:     3,
  },
};

// ── FVG 3-Timeframe Bear  (D1 → H4 → M30 → SELL) ────────────────────────────
export const FVG_3TF_BEAR: MtfOrchestratorConfig = {
  id:          "fvg-3tf-bear",
  name:        "MTF_FVG_3TF_Bear",
  description:
    "D1 FVG bear confirm → H4 FVG bear confirm → M30 FVG entry signal → SELL. " +
    "Mirror of the 3-TF bull strategy. " +
    "Run alongside MTF_FVG_3TF_Bull with a different magic number to trade both directions.",
  direction: "BEAR",
  steps: [
    {
      label:        "D1 FVG Bear Confirm",
      moduleName:   "FVG_State_Module",
      timeframe:    "PERIOD_D1",
      lookback:     200,
      bufIdx:       1,   // BearConfirmBuf
      triggerValue: 1.0,
      expiryBars:   10,
    },
    {
      label:        "H4 FVG Bear Confirm",
      moduleName:   "FVG_State_Module",
      timeframe:    "PERIOD_H4",
      lookback:     300,
      bufIdx:       1,
      triggerValue: 1.0,
      expiryBars:   24,
    },
    {
      label:        "M30 FVG Entry Signal",
      moduleName:   "FVG_State_Module",
      timeframe:    "PERIOD_M30",
      lookback:     500,
      bufIdx:       1,
      triggerValue: 1.0,
      expiryBars:   40,
    },
  ],
  execution: {
    slBufIdx:     3,   // BearSLBuf
    magic:        20250602,
    riskPct:      1.0,
    rr:           2.0,
    breakevenR:   0.5,
    maxTrades:    1,
    maxSpreadPts: 20,
    slippage:     3,
  },
};

// ── FVG 2-Timeframe Bull  (H4 → M30 → BUY) ───────────────────────────────────
export const FVG_2TF_BULL: MtfOrchestratorConfig = {
  id:          "fvg-2tf-bull",
  name:        "MTF_FVG_2TF_Bull",
  description:
    "H4 FVG bull confirm → M30 FVG entry signal → BUY. " +
    "Shorter chain for intraday traders: H4 sets the bias, M30 provides the entry.",
  direction: "BULL",
  steps: [
    {
      label:        "H4 FVG Bull Confirm",
      moduleName:   "FVG_State_Module",
      timeframe:    "PERIOD_H4",
      lookback:     300,
      bufIdx:       0,
      triggerValue: 1.0,
      expiryBars:   24,
    },
    {
      label:        "M30 FVG Entry Signal",
      moduleName:   "FVG_State_Module",
      timeframe:    "PERIOD_M30",
      lookback:     500,
      bufIdx:       0,
      triggerValue: 1.0,
      expiryBars:   40,
    },
  ],
  execution: {
    slBufIdx:     2,
    magic:        20250603,
    riskPct:      1.0,
    rr:           2.0,
    breakevenR:   0.5,
    maxTrades:    2,
    maxSpreadPts: 20,
    slippage:     3,
  },
};

// ── FVG 2-Timeframe Bear  (H4 → M30 → SELL) ──────────────────────────────────
export const FVG_2TF_BEAR: MtfOrchestratorConfig = {
  id:          "fvg-2tf-bear",
  name:        "MTF_FVG_2TF_Bear",
  description:
    "H4 FVG bear confirm → M30 FVG entry signal → SELL. " +
    "Mirror of the 2-TF bull strategy.",
  direction: "BEAR",
  steps: [
    {
      label:        "H4 FVG Bear Confirm",
      moduleName:   "FVG_State_Module",
      timeframe:    "PERIOD_H4",
      lookback:     300,
      bufIdx:       1,
      triggerValue: 1.0,
      expiryBars:   24,
    },
    {
      label:        "M30 FVG Entry Signal",
      moduleName:   "FVG_State_Module",
      timeframe:    "PERIOD_M30",
      lookback:     500,
      bufIdx:       1,
      triggerValue: 1.0,
      expiryBars:   40,
    },
  ],
  execution: {
    slBufIdx:     3,
    magic:        20250604,
    riskPct:      1.0,
    rr:           2.0,
    breakevenR:   0.5,
    maxTrades:    2,
    maxSpreadPts: 20,
    slippage:     3,
  },
};
