/**
 * Management Brain Template
 *
 * Generated by: gen-management.ts
 * Purpose: Hold risk/exit configuration
 *
 * This brain is mostly static (set once from inputs).
 */

export const MANAGEMENT_BRAIN_TEMPLATE = `
//+------------------------------------------------------------------+
//| Management Brain: Risk & Exit Configuration                      |
//+------------------------------------------------------------------+

ManagementBrainState gMgmtState = {
   {{ riskPercent }},     // riskPercent
   {{ rewardRisk }},      // rewardRisk
   {{ stopBuffer }},      // stopBuffer
   {{ breakEvenEnabled }}, // breakEvenEnabled
   {{ breakEvenAtR }},    // breakEvenAtR
   {{ maxOpenTrades }}    // maxOpenTrades
};

void Management_Brain_ManageBreakEven()
{
   {{ breakEvenLogic }}
}
`;
