/**
 * Setup Brain Template
 *
 * Generated by: gen-setup-brain.ts
 * Purpose: Detect and confirm trading zones
 *
 * Outputs SetupBrainState showing active zone and SL hint.
 */

export const SETUP_BRAIN_TEMPLATE = `
//+------------------------------------------------------------------+
//| Setup Brain: {{ modulesLabel }} @ {{ timeframe }}                            |
//| Detects zones and updates gSetupState                            |
//+------------------------------------------------------------------+

// Setup Brain State
SetupBrainState gSetupState = {false, 0, 0, 0, "Initializing"};

// Module-specific globals (filled by generator)
{{ setupGlobals }}

SetupBrainState Setup_Brain_Execute()
{
   SetupBrainState state = {false, 0, 0, 0, ""};
   datetime barTime = iTime(InpSymbol, InpSetupTF, 1);
   double bid = SymbolInfoDouble(InpSymbol, SYMBOL_BID);
   double ask = SymbolInfoDouble(InpSymbol, SYMBOL_ASK);

   // Module zone detection logic (filled by generator)
{{ setupDetectionLogic }}

   state.zoneTime = barTime;
   return state;
}
`;
