/**
 * Direction Brain Template
 *
 * Generated by: gen-direction-brain.ts
 * Purpose: Detect market bias and update gDirState
 *
 * This template is filled in by the generator with specific module logic
 * (CHoCH, BOS, EMA, etc.). The brain runs on its own timeframe and
 * produces a DirectionBrainState output.
 */

export const DIRECTION_BRAIN_TEMPLATE = `
//+------------------------------------------------------------------+
//| Direction Brain: {{ modulesLabel }} @ {{ timeframe }}                          |
//| Detects market bias and updates gDirState                        |
//+------------------------------------------------------------------+

// Direction Brain State
DirectionBrainState gDirState = {0, 0, "Initializing"};

// Module-specific globals (filled by generator)
{{ directionGlobals }}

DirectionBrainState Direction_Brain_Execute()
{
   DirectionBrainState state = {0, 0, ""};
   datetime barTime = iTime(InpSymbol, InpDirectionTF, 1);

   // Module detection logic (filled by generator)
{{ directionDetectionLogic }}

   state.lastUpdate = barTime;
   return state;
}
`;
