/**
 * Execution Brain Template
 *
 * Generated by: gen-execution-brain.ts
 * Purpose: Detect entry signals
 *
 * Outputs ExecutionBrainState showing confirmed entry signal.
 * This brain checks confluence with Direction and Setup before returning
 * a trade signal.
 */

export const EXECUTION_BRAIN_TEMPLATE = `
//+------------------------------------------------------------------+
//| Execution Brain: {{ modulesLabel }} @ {{ timeframe }}                       |
//| Detects entries and updates gExecState                           |
//+------------------------------------------------------------------+

// Execution Brain State
ExecutionBrainState gExecState = {false, 0, 0, 0, 0, 0, "Initializing"};

// Module-specific globals (filled by generator)
{{ executionGlobals }}

ExecutionBrainState Execution_Brain_Execute(DirectionBrainState dirState, SetupBrainState setupState)
{
   ExecutionBrainState state = {false, 0, 0, 0, 0, 0, ""};
   datetime barTime = iTime(InpSymbol, InpExecTF, 1);
   double bid = SymbolInfoDouble(InpSymbol, SYMBOL_BID);
   double ask = SymbolInfoDouble(InpSymbol, SYMBOL_ASK);

   // Module signal detection logic (filled by generator)
{{ executionDetectionLogic }}

   state.signalTime = barTime;
   return state;
}

void Execution_Brain_ExecuteEntry(ExecutionBrainState execState, DirectionBrainState dirState, SetupBrainState setupState)
{
   // Confluence gate
   bool canTrade = (dirState.bias != 0) && setupState.active && execState.signalReady;

   if(!canTrade) {
      PrintFormat("[GATE] Blocked: dir=%d setup=%d exec=%d",
                   dirState.bias, setupState.active, execState.signalReady);
      return;
   }

   // Entry logic (filled by generator)
{{ executionEntryLogic }}
}
`;
