/**
 * EA Scaffold Template
 *
 * Generated by: gen-ea.ts
 * Purpose: EA wrapper (header, OnInit, OnDeinit)
 *
 * This is the complete EA file. Generators fill in:
 * - Inputs (from config)
 * - Globals (brain states + helpers)
 * - Functions (all brains + assembler)
 */

export const EA_SCAFFOLD_TEMPLATE = `
//+------------------------------------------------------------------+
//| {{ eaName }}.mq5
//| Generated by EAbuilder2 — 4-Brain Architecture
//|
//| Direction : {{ directionDesc }}
//| Setup     : {{ setupDesc }}
//| Execution : {{ executionDesc }}
//| Management: {{ managementDesc }}
//+------------------------------------------------------------------+
#property copyright "Generated by EAbuilder2"
#property version   "1.00"
#property strict

#include <Trade/Trade.mqh>
CTrade trade;

// ─── INPUTS ─────────────────────────────────────────────────────
{{ inputs }}

// ─── GLOBALS ─────────────────────────────────────────────────────
{{ globalStates }}
{{ globalHelpers }}

// ─── BRAIN STATE TYPES ───────────────────────────────────────────
{{ brainStateTypes }}

// ─── HELPERS ─────────────────────────────────────────────────────
{{ helpers }}

// ─── BRAIN IMPLEMENTATIONS ───────────────────────────────────────
{{ directionBrain }}

{{ setupBrain }}

{{ executionBrain }}

{{ managementBrain }}

// ─── ONTICK ASSEMBLER ───────────────────────────────────────────
{{ ontickAssembler }}

// ─── LIFECYCLE ───────────────────────────────────────────────────
int OnInit()
{
   trade.SetExpertMagicNumber((ulong)InpMagic);
   trade.SetTypeFillingBySymbol(InpSymbol);
   return INIT_SUCCEEDED;
}

void OnDeinit(const int reason) {}
`;
