/**
 * OnTick Assembler Template
 *
 * Generated by: gen-ea-assembler.ts
 * Purpose: Orchestrate the three brains and execute trades
 *
 * This is the main event loop. Each brain runs independently on its
 * own timeframe, then the assembler checks gates and executes.
 */

export const ONTICK_ASSEMBLER_TEMPLATE = `
static datetime lastDirBar   = 0;
static datetime lastSetupBar = 0;
static datetime lastExecBar  = 0;

void OnTick()
{
   // ─── BREAK-EVEN MANAGEMENT (always runs) ───
   Management_Brain_ManageBreakEven();

   // ─── DIRECTION BRAIN ({{ directionTF }}) ───
   datetime dirBar = iTime(InpSymbol, InpDirectionTF, 0);
   if(dirBar != lastDirBar)
   {
      lastDirBar = dirBar;
      gDirState = Direction_Brain_Execute();
      PrintFormat("[D{{ directionTF }}] bias=%d %s", gDirState.bias, gDirState.reason);
   }

   // ─── SETUP BRAIN ({{ setupTF }}) ───
   {{ setupBrainCheck }}

   // ─── EXECUTION BRAIN ({{ executionTF }}) ───
   datetime execBar = iTime(InpSymbol, InpExecTF, 0);
   if(execBar != lastExecBar)
   {
      lastExecBar = execBar;
      gExecState = Execution_Brain_Execute(gDirState, gSetupState);

      // Log confluence gate
      bool canTrade = (gDirState.bias != 0) && (gSetupState.active || !{{ hasSetup }}) && gExecState.signalReady;
      PrintFormat("[M{{ executionTF }}] Gate: dir=%d setup=%d exec=%d → %s",
                   gDirState.bias, gSetupState.active, gExecState.signalReady,
                   canTrade ? "TRADE" : "BLOCKED");

      if(canTrade)
      {
         Execution_Brain_ExecuteEntry(gExecState, gDirState, gSetupState);
      }
   }
}
`;
