/**
 * Main EA Generator (gen-ea.ts)
 *
 * Orchestrates all modular brain generators and assembles them into
 * a complete, compilable 4-brain EA with real detection logic.
 *
 * PHASE 0: Uses modular generators that produce inline MQL5 detection code
 */

import type { FourBrainConfig, MQL5CodeGenParams } from "@/types/blueprint";
import { genDirectionBrain } from "./gen-direction-brain";
import { genSetupBrain } from "./gen-setup-brain";
import { genExecutionBrain } from "./gen-execution-brain";

export function generateEA(params: MQL5CodeGenParams): string {
  const {
    eaName,
    config: fourBrainConfig,
    globalSymbol = "EURUSD",
    globalMagic = 123456,
  } = params;

  // Generate all brain implementations using modular generators
  const directionBrainCode = genDirectionBrain(fourBrainConfig.direction);
  const setupBrainCode = genSetupBrain(fourBrainConfig.setup);
  const executionBrainCode = genExecutionBrain(fourBrainConfig.execution);

  const directionModules = fourBrainConfig.direction?.modules?.join(" + ").toUpperCase() || "NONE";
  const directionTF = fourBrainConfig.direction?.timeframe || "D1";
  const setupModules = fourBrainConfig.setup?.modules?.join(" + ").toUpperCase() || "NONE";
  const setupTF = fourBrainConfig.setup?.timeframe || "H4";
  const executionModules = fourBrainConfig.execution?.modules?.join(" + ").toUpperCase() || "NONE";
  const executionTF = fourBrainConfig.execution?.timeframe || "H1";

  const riskPercent = fourBrainConfig.management?.riskPercent || 1.0;
  const rewardRisk = fourBrainConfig.management?.rewardRisk || 1.5;
  const stopBuffer = fourBrainConfig.management?.stopBuffer || 0.001;

  // Generate the complete EA with modular brain implementations
  const ea = `//+------------------------------------------------------------------+
//| ${eaName}.mq5
//| Generated by EAbuilder2 - 4-Brain Architecture
//|
//| Direction : ${directionModules} @ ${directionTF}
//| Setup     : ${setupModules} @ ${setupTF}
//| Execution : ${executionModules} @ ${executionTF}
//| Management: ${riskPercent}% risk - ${rewardRisk}R TP
//+------------------------------------------------------------------+
#property copyright "Generated by EAbuilder2"
#property version   "1.00"
#property strict

#include <Trade/Trade.mqh>
CTrade trade;

//--- Inputs
input string   InpSymbol      = "${globalSymbol}";
input ulong    InpMagic       = ${globalMagic};
input ENUM_TIMEFRAMES InpDirectionTF = PERIOD_${directionTF};
input ENUM_TIMEFRAMES InpSetupTF     = PERIOD_${setupTF};
input ENUM_TIMEFRAMES InpExecTF      = PERIOD_${executionTF};
input double   InpRiskPercent = ${riskPercent};
input double   InpRewardRisk  = ${rewardRisk};
input double   InpStopBuffer  = ${stopBuffer};

//--- Global state
bool gSetupActive = false;  // Setup brain output: zone detected?
bool gExecSignal = false;   // Execution brain output: entry signal ready?

// Brain implementations (auto-generated from modules)
${directionBrainCode}

${setupBrainCode}

${executionBrainCode}

//--- OnInit
int OnInit()
{
   trade.SetExpertMagicNumber((ulong)InpMagic);
   trade.SetTypeFillingBySymbol(InpSymbol);

   Direction_Brain_Init();
   Print("[EA] ${eaName} initialized");
   Print("[CONFIG] Direction: ${directionModules} @ ${directionTF}");
   Print("[CONFIG] Setup: ${setupModules} @ ${setupTF}");
   Print("[CONFIG] Execution: ${executionModules} @ ${executionTF}");

   return INIT_SUCCEEDED;
}

//--- OnTick (main event loop)
void OnTick()
{
   // Direction Brain: detect bias on its timeframe
   static datetime lastDirBar = 0;
   datetime dirBar = iTime(InpSymbol, InpDirectionTF, 0);
   if(dirBar != lastDirBar)
   {
      lastDirBar = dirBar;
      Direction_Brain_Execute();
      PrintFormat("[D${directionTF}] bias=%d", gBias);
   }

   // Setup Brain: detect zone on its timeframe
   static datetime lastSetupBar = 0;
   datetime setupBar = iTime(InpSymbol, InpSetupTF, 0);
   if(setupBar != lastSetupBar)
   {
      lastSetupBar = setupBar;
      Setup_Brain_Execute();
      PrintFormat("[S${setupTF}] setup_active=%d", gSetupActive ? 1 : 0);
   }

   // Execution Brain: detect entry signal on its timeframe
   static datetime lastExecBar = 0;
   datetime execBar = iTime(InpSymbol, InpExecTF, 0);
   if(execBar != lastExecBar)
   {
      lastExecBar = execBar;
      Execution_Brain_Execute();
      PrintFormat("[E${executionTF}] exec_signal=%d", gExecSignal ? 1 : 0);

      // Confluence gate: all must agree
      bool canTrade = (gBias != 0) && (gSetupActive || ${fourBrainConfig.setup ? 'false' : 'true'}) && gExecSignal;
      PrintFormat("[GATE] bias=%d setup=%d exec=%d -> %s", gBias, gSetupActive ? 1 : 0, gExecSignal ? 1 : 0, canTrade ? "TRADE" : "BLOCKED");

      if(canTrade)
      {
         // TODO: Execute entry logic with proper risk management
      }
   }
}

void OnDeinit(const int reason)
{
   Print("[EA] " + InpSymbol + " terminated");
}
`;

  return ea;
}
