/**
 * Main EA Generator (gen-ea.ts)
 *
 * Orchestrates all modular generators:
 * 1. gen-direction-brain.ts
 * 2. gen-setup-brain.ts
 * 3. gen-execution-brain.ts
 * 4. gen-management-brain.ts
 * 5. gen-ea-assembler.ts
 *
 * Then assembles them into the complete EA using EA_SCAFFOLD_TEMPLATE.
 */

import type { FourBrainConfig, MQL5CodeGenParams } from "@/types/blueprint";
import { genDirectionBrain } from "./gen-direction-brain";
import { genSetupBrain } from "./gen-setup-brain";
import { genExecutionBrain } from "./gen-execution-brain";
import { genManagementBrain } from "./gen-management-brain";
import { genEAAssembler } from "./gen-ea-assembler";
import { EA_SCAFFOLD_TEMPLATE } from "@/templates/ea-scaffold.mql5";
import { genInputs } from "./gen-inputs";
import { genHelpers } from "./gen-helpers";
import { genBrainStateTypes } from "./gen-brain-state-types";

export function generateEA(params: MQL5CodeGenParams): string {
  const {
    eaName,
    config: fourBrainConfig,
    globalSymbol = "EURUSD",
    globalMagic = 123456,
  } = params;

  // For now, generate a minimal, compilable 4-brain EA skeleton
  // PHASE 0 INTERIM: Placeholder logic until module-specific logic is implemented

  const directionModules = fourBrainConfig.direction?.modules?.join(" + ").toUpperCase() || "NONE";
  const directionTF = fourBrainConfig.direction?.timeframe || "D1";
  const setupModules = fourBrainConfig.setup?.modules?.join(" + ").toUpperCase() || "NONE";
  const setupTF = fourBrainConfig.setup?.timeframe || "H4";
  const executionModules = fourBrainConfig.execution?.modules?.join(" + ").toUpperCase() || "NONE";
  const executionTF = fourBrainConfig.execution?.timeframe || "H1";

  const riskPercent = fourBrainConfig.management?.riskPercent || 1.0;
  const rewardRisk = fourBrainConfig.management?.rewardRisk || 1.5;
  const stopBuffer = fourBrainConfig.management?.stopBuffer || 0.001;

  // Generate minimal, compilable MQL5 EA
  const ea = `//+------------------------------------------------------------------+
//| ${eaName}.mq5
//| Generated by EAbuilder2 — 4-Brain Architecture (PHASE 0)
//|
//| Direction : ${directionModules} @ ${directionTF}
//| Setup     : ${setupModules} @ ${setupTF}
//| Execution : ${executionModules} @ ${executionTF}
//| Management: ${riskPercent}% risk · ${rewardRisk}R TP
//+------------------------------------------------------------------+
#property copyright "Generated by EAbuilder2"
#property version   "1.00"
#property strict

#include <Trade/Trade.mqh>
CTrade trade;

//--- Inputs
input string   InpSymbol      = "${globalSymbol}";
input ulong    InpMagic       = ${globalMagic};
input ENUM_TIMEFRAMES InpDirectionTF = PERIOD_${directionTF};
input ENUM_TIMEFRAMES InpSetupTF     = PERIOD_${setupTF};
input ENUM_TIMEFRAMES InpExecTF      = PERIOD_${executionTF};
input double   InpRiskPercent = ${riskPercent};
input double   InpRewardRisk  = ${rewardRisk};
input double   InpStopBuffer  = ${stopBuffer};

//--- Global state
int gBias = 0;        // Direction brain output: 1=BULL, -1=BEAR, 0=NEUTRAL
bool gSetupActive = false;  // Setup brain output: zone detected?
bool gExecSignal = false;   // Execution brain output: entry signal ready?

//--- OnInit
int OnInit()
{
   trade.SetExpertMagicNumber((ulong)InpMagic);
   trade.SetTypeFillingBySymbol(InpSymbol);

   Print("[EA] ${eaName} initialized");
   Print("[CONFIG] Direction: ${directionModules} @ ${directionTF}");
   Print("[CONFIG] Setup: ${setupModules} @ ${setupTF}");
   Print("[CONFIG] Execution: ${executionModules} @ ${executionTF}");

   return INIT_SUCCEEDED;
}

//--- OnTick (main event loop)
void OnTick()
{
   // PHASE 0 PLACEHOLDER: Real detection logic will be generated per-brain

   // Direction Brain: detect bias
   static datetime lastDirBar = 0;
   datetime dirBar = iTime(InpSymbol, InpDirectionTF, 0);
   if(dirBar != lastDirBar)
   {
      lastDirBar = dirBar;
      // TODO: Direction detection for ${directionModules}
      gBias = 0;  // Placeholder
      PrintFormat("[D${directionTF}] bias=%d", gBias);
   }

   // Setup Brain: detect zone
   static datetime lastSetupBar = 0;
   datetime setupBar = iTime(InpSymbol, InpSetupTF, 0);
   if(setupBar != lastSetupBar)
   {
      lastSetupBar = setupBar;
      // TODO: Setup detection for ${setupModules}
      gSetupActive = false;  // Placeholder
      PrintFormat("[S${setupTF}] setup_active=%d", gSetupActive ? 1 : 0);
   }

   // Execution Brain: detect entry signal
   static datetime lastExecBar = 0;
   datetime execBar = iTime(InpSymbol, InpExecTF, 0);
   if(execBar != lastExecBar)
   {
      lastExecBar = execBar;
      // TODO: Entry detection for ${executionModules}
      gExecSignal = false;  // Placeholder
      PrintFormat("[E${executionTF}] exec_signal=%d", gExecSignal ? 1 : 0);

      // Confluence gate: all must agree
      bool canTrade = (gBias != 0) && (gSetupActive || ${fourBrainConfig.setup ? 'false' : 'true'}) && gExecSignal;
      PrintFormat("[GATE] bias=%d setup=%d exec=%d → %s", gBias, gSetupActive ? 1 : 0, gExecSignal ? 1 : 0, canTrade ? "TRADE" : "BLOCKED");

      if(canTrade)
      {
         // TODO: Execute entry logic
      }
   }
}

void OnDeinit(const int reason)
{
   Print("[EA] " + InpSymbol + " terminated");
}
`;

  return ea;
}
