/**
 * MQL5 emit + static-lint verification.
 *
 *   npx tsx scripts/verify-mql5.ts
 *
 * Emits every recently-built generator's output to verify/mql5/*.mq5 so they can
 * be dropped into MetaEditor, and runs a static lint pass for the MQL5 pitfalls
 * listed in CLAUDE.md (MQL4-isms, brace/paren balance, bare Ask/Bid, etc.).
 *
 * Static lint is NOT a compiler — a clean report means "no obvious red flags",
 * the real gate is still MetaEditor F7. But it catches the cheap mistakes.
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

// Standalone full-indicator generators (each returns a complete .mq5)
import { generateMissDetector } from "../src/lib/smc-modules/miss-detector";
import { generateMissStateModule } from "../src/lib/smc-modules/miss-state-module";
import { generateRssSrrDetector } from "../src/lib/smc-modules/rss-srr-detector";
import { generateRssSrrStateModule } from "../src/lib/smc-modules/rss-srr-state-module";
import { generateFvgLiquidityDetector } from "../src/lib/smc-modules/fvg-liquidity-detector";
import { generateObLiquidityDetector } from "../src/lib/smc-modules/ob-liquidity-detector";
import { generateBbLiquidityDetector } from "../src/lib/smc-modules/bb-liquidity-detector";
import { generateObFvgDetector } from "../src/lib/smc-modules/ob-fvg-detector";
import { generateUnicornDetector } from "../src/lib/smc-modules/unicorn-detector";
import { generateRsiHiddenDivergenceDetector } from "../src/lib/indicator-modules/rsi-hidden-divergence-detector";
import { generateRsiHiddenDivergenceStateModule } from "../src/lib/indicator-modules/rsi-hidden-divergence-state-module";
import { generateEngulfingDetector } from "../src/lib/smc-modules/engulfing-detector";
import { generateStrongEngulfingDetector } from "../src/lib/smc-modules/strong-engulfing-detector";
import { generateRbrDbdDetector } from "../src/lib/smc-modules/rbr-dbd-detector";

// Inline state-machine fragment generators
import { genRsiHdSM } from "../src/generators/gen-rsi-hd-sm";
import { genObFvgSM } from "../src/generators/gen-obfvg-sm";
import { genEgSM } from "../src/generators/gen-eg-sm";

// Full 4-brain assembler (AI path)
import { generateEA } from "../src/generators/gen-ea";
import type { FourBrainConfig, MQL5CodeGenParams } from "../src/types/blueprint";
import type { AiBrainWiring } from "../src/lib/api-client";
import { MODULE_LIBRARY, MODULE_UI_PARAMS } from "../src/lib/module-library";
import {
  MODULE_CONTRACTS,
  getModuleContract,
  moduleContractAllowsSmFunction,
} from "../src/lib/module-contracts";

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT = resolve(__dirname, "..", "verify", "mql5");
mkdirSync(OUT, { recursive: true });

// ── Wrap the inline SM fragment in a minimal compilable test indicator ────────
function wrapInlineSM(name: string, fragment: string, resetCall: string, tickCall: string): string {
  return `//+------------------------------------------------------------------+
//| ${name} — inline-SM compile harness (generated by verify-mql5)  |
//+------------------------------------------------------------------+
#property strict
#property indicator_chart_window
#property indicator_plots 0

string InpSymbol = "EURUSD";   // the real EA supplies this as an input
${fragment}
int OnInit() { InpSymbol = _Symbol; ${resetCall} return INIT_SUCCEEDED; }
void OnDeinit(const int reason) {}
int OnCalculate(const int rates_total, const int prev_calculated,
                const datetime &time[], const double &open[],
                const double &high[], const double &low[],
                const double &close[], const long &tick_volume[],
                const long &volume[], const int &spread[])
{
   static datetime _last = 0;
   datetime _t = iTime(InpSymbol, PERIOD_CURRENT, 0);
   if(_t != _last) { _last = _t; ${tickCall} }
   return rates_total;
}
`;
}

interface Item {
  file: string;
  code: string;
}
const items: Item[] = [
  { file: "Miss_Detector.mq5", code: generateMissDetector() },
  { file: "Miss_State_Module.mq5", code: generateMissStateModule() },
  { file: "RSS_SRR_Detector.mq5", code: generateRssSrrDetector() },
  { file: "RSS_SRR_State_Module.mq5", code: generateRssSrrStateModule() },
  { file: "FVG_Liquidity_Detector.mq5", code: generateFvgLiquidityDetector() },
  { file: "OB_Liquidity_Detector.mq5", code: generateObLiquidityDetector() },
  { file: "BB_Liquidity_Detector.mq5", code: generateBbLiquidityDetector() },
  { file: "OB_FVG_Detector.mq5", code: generateObFvgDetector() },
  { file: "Unicorn_Detector.mq5", code: generateUnicornDetector() },
  { file: "RSI_Hidden_Divergence_Detector.mq5", code: generateRsiHiddenDivergenceDetector() },
  {
    file: "RSI_Hidden_Divergence_State_Module.mq5",
    code: generateRsiHiddenDivergenceStateModule(),
  },
  {
    file: "ENG_Detector.mq5",
    code: generateEngulfingDetector(),
  },
  {
    file: "SEG_Detector.mq5",
    code: generateStrongEngulfingDetector(),
  },
  {
    file: "RBR_DBD_Detector.mq5",
    code: generateRbrDbdDetector(),
  },
  {
    file: "_TEST_RSIHDSM_M15.mq5",
    code: wrapInlineSM(
      "RSIHDSM M15",
      genRsiHdSM("M15", "PERIOD_M15", "M15"),
      "RSIHDSM_M15_Reset();",
      "RSIHDSM_M15_Tick(50);",
    ),
  },
  {
    file: "_TEST_OBFVGSM_M15.mq5",
    code: wrapInlineSM(
      "OBFVGSM M15",
      genObFvgSM("M15", "PERIOD_M15", "M15"),
      "OBFVGSM_M15_Reset();",
      "OBFVGSM_M15_Tick(50);",
    ),
  },
  // ── EG+EF (Engulfing / Engulfing Failed) — M5 instance ─────────────────────
  {
    file: "_TEST_EGSM_M5.mq5",
    code: wrapInlineSM(
      "EGSM M5 (Engulfing + Engulfing Failed)",
      genEgSM("M5", "PERIOD_M5", "M5", 3, 100),
      "EGSM_M5_Reset();",
      "EGSM_M5_Tick(10);",
    ),
  },
  // ── EG+EF — H4 instance (Direction / Setup role) ───────────────────────────
  {
    file: "_TEST_EGSM_H4.mq5",
    code: wrapInlineSM(
      "EGSM H4 (Engulfing + Engulfing Failed)",
      genEgSM("H4", "PERIOD_H4", "H4", 3, 200),
      "EGSM_H4_Reset();",
      "EGSM_H4_Tick(20);",
    ),
  },
];

// ── Static lint ───────────────────────────────────────────────────────────────
function lint(code: string): string[] {
  const warn: string[] = [];
  const lines = code.split("\n");

  // brace / paren balance
  const count = (re: RegExp) => (code.match(re) ?? []).length;
  if (count(/\{/g) !== count(/\}/g))
    warn.push(`brace imbalance: ${count(/\{/g)} { vs ${count(/\}/g)} }`);
  if (count(/\(/g) !== count(/\)/g))
    warn.push(`paren imbalance: ${count(/\(/g)} ( vs ${count(/\)/g)} )`);

  // MQL4-isms / forbidden patterns (per CLAUDE.md)
  const pat: Array<[RegExp, string]> = [
    [/\b(Close|Open|High|Low|Time)\s*\[/g, "MQL4 series access (use iClose/iOpen/… )"],
    [/(?<![A-Za-z_.])(Ask|Bid)\b(?!\w)/g, "bare Ask/Bid (use SymbolInfoDouble SYMBOL_ASK/BID)"],
    [/\bSetMagicNumber\b/g, "SetMagicNumber (use trade.SetExpertMagicNumber)"],
    [/\bGetPointer\s*\(/g, "GetPointer on struct"],
  ];
  for (const [re, msg] of pat) {
    const hits: number[] = [];
    lines.forEach((ln, i) => {
      if (re.test(ln)) hits.push(i + 1);
      re.lastIndex = 0;
    });
    if (hits.length)
      warn.push(`${msg} @ lines ${hits.slice(0, 6).join(",")}${hits.length > 6 ? "…" : ""}`);
  }

  // struct defined inside a function (heuristic: 'struct' appearing after a non-zero brace depth)
  let depth = 0;
  lines.forEach((ln, i) => {
    const before = depth;
    depth += (ln.match(/\{/g) ?? []).length - (ln.match(/\}/g) ?? []).length;
    if (before > 0 && /^\s*struct\s+\w/.test(ln))
      warn.push(`struct declared inside a block @ line ${i + 1}`);
  });

  return warn;
}

// ── Integration test: a full 4-brain EA using rsi_hd via the AI path ──────────
// sm_configs is EMPTY on purpose — reconcileStateMachines() must auto-embed
// RSIHDSM_M15 from the setup_brain reference, and OnInit must auto-call Reset.
function buildAiEa(): { code: string; checks: Array<[string, boolean]> } {
  const config: FourBrainConfig = {
    direction: { modules: ["bos"], timeframe: "H4" },
    setup: { modules: ["rsi_hd"], timeframe: "M15" },
    execution: { modules: ["fvg_inversion"], timeframe: "M5" },
    management: {
      riskPercent: 1.0,
      rewardRisk: 3.0,
      stopBuffer: 50,
      breakEvenEnabled: true,
      breakEvenAtR: 1.5,
      maxOpenTrades: 3,
    },
  };
  const aiWiring: AiBrainWiring = {
    direction_brain: `void Direction_Brain_Execute() { gBias = 1; }`,
    setup_brain: `void Setup_Brain_Execute() {
   RSIHDSM_M15_Tick(50);
   if(RSIHDSM_M15_BullJustConfirmed()) { gSetupActive = true; gSetupDir = 1; gSetupSLHint = RSIHDSM_M15_BullConfirmSL(); }
   else if(RSIHDSM_M15_BearJustConfirmed()) { gSetupActive = true; gSetupDir = -1; gSetupSLHint = RSIHDSM_M15_BearConfirmSL(); }
}`,
    execution_brain: `void Execution_Brain_Execute() {
   if(gSetupActive) { gExecSignal = true; gExecDir = gSetupDir; gExecSL = gSetupSLHint; }
}`,
    required_sms: ["RSIHDSM_M15"],
    sm_configs: {}, // intentionally empty → must be reconciled
  };
  const params: MQL5CodeGenParams = {
    eaName: "RSI_HD_Continuation_Test",
    config,
    globalSymbol: "EURUSD",
    globalMagic: 990777,
    aiWiring,
  };
  const code = generateEA(params);
  const checks: Array<[string, boolean]> = [
    ["SM auto-embedded (reconcile)", code.includes("void RSIHDSM_M15_Tick")],
    ["SM Reset auto-called in OnInit", code.includes("RSIHDSM_M15_Reset();")],
    ["RSI handle present", code.includes("iRSI(InpSymbol, PERIOD_M15")],
    ["setup brain wired", code.includes("RSIHDSM_M15_BullJustConfirmed()")],
  ];
  return { code, checks };
}

let totalWarn = 0;
console.log(`\nEmitting ${items.length} files → ${OUT}\n`);
for (const it of items) {
  writeFileSync(resolve(OUT, it.file), it.code, "utf8");
  const w = lint(it.code);
  totalWarn += w.length;
  const tag = w.length === 0 ? "OK  " : "WARN";
  console.log(`[${tag}] ${it.file}  (${it.code.split("\n").length} lines)`);
  for (const m of w) console.log(`        • ${m}`);
}
// ── AI-path integration: OB+FVG as Setup→Execution via the AI path ────────────
function buildObFvgAiEa(): { code: string; checks: Array<[string, boolean]> } {
  const config: FourBrainConfig = {
    direction: { modules: ["bos"], timeframe: "H4" },
    setup: { modules: ["ob_fvg"], timeframe: "M15" },
    execution: { modules: ["ob_fvg"], timeframe: "M15" },
    management: {
      riskPercent: 1.0,
      rewardRisk: 3.0,
      stopBuffer: 50,
      breakEvenEnabled: true,
      breakEvenAtR: 1.5,
      maxOpenTrades: 3,
    },
  };
  const aiWiring: AiBrainWiring = {
    direction_brain: `void Direction_Brain_Execute() { gBias = 1; }`,
    setup_brain: `void Setup_Brain_Execute() {
   OBFVGSM_M15_Tick(80);
   if(OBFVGSM_M15_HasActiveBull()) { gSetupActive = true; gSetupDir = 1; gSetupSLHint = OBFVGSM_M15_ActiveBullSL(); }
   else if(OBFVGSM_M15_HasActiveBear()) { gSetupActive = true; gSetupDir = -1; gSetupSLHint = OBFVGSM_M15_ActiveBearSL(); }
}`,
    execution_brain: `void Execution_Brain_Execute() {
   if(OBFVGSM_M15_BullJustConfirmed()) { gExecSignal = true; gExecDir = 1;  gExecSL = OBFVGSM_M15_BullConfirmSL(); }
   else if(OBFVGSM_M15_BearJustConfirmed()) { gExecSignal = true; gExecDir = -1; gExecSL = OBFVGSM_M15_BearConfirmSL(); }
}`,
    required_sms: ["OBFVGSM_M15"],
    sm_configs: {},
  };
  const code = generateEA({
    eaName: "OB_FVG_Setup_Test",
    config,
    globalSymbol: "EURUSD",
    globalMagic: 990778,
    aiWiring,
  });
  const checks: Array<[string, boolean]> = [
    ["SM auto-embedded (reconcile)", code.includes("void OBFVGSM_M15_Tick")],
    ["SM Reset auto-called in OnInit", code.includes("OBFVGSM_M15_Reset();")],
    ["setup brain wired", code.includes("OBFVGSM_M15_HasActiveBull()")],
    ["execution entry wired", code.includes("OBFVGSM_M15_BullJustConfirmed()")],
  ];
  return { code, checks };
}

// ── Run the AI-path integration tests ─────────────────────────────────────────
function runAiTest(
  title: string,
  file: string,
  build: () => { code: string; checks: Array<[string, boolean]> },
) {
  console.log(`\n── AI-path integration: ${title} ──`);
  try {
    const { code, checks } = build();
    writeFileSync(resolve(OUT, file), code, "utf8");
    const lw = lint(code);
    console.log(`[${lw.length ? "WARN" : "OK  "}] ${file}  (${code.split("\n").length} lines)`);
    for (const m of lw) console.log(`        • ${m}`);
    totalWarn += lw.length;
    for (const [name, ok] of checks) console.log(`        ${ok ? "✓" : "✗"} ${name}`);
    if (checks.some(([, ok]) => !ok)) totalWarn++;
  } catch (e) {
    console.log(`[FAIL] assembler threw: ${(e as Error).message}`);
    totalWarn++;
  }
}
runAiTest("RSI HD as Setup Brain", "RSI_HD_Continuation_Test.mq5", buildAiEa);
runAiTest("OB+FVG as Setup→Execution", "OB_FVG_Setup_Test.mq5", buildObFvgAiEa);

// ── EMA cross→retest sequence (M15 cross → M5 cross setup → M5 retest/confirm) ─
runAiTest(
  "EMA cross→retest SM (M15 bias → M5 cross → retest → confirm)",
  "EMA_CrossRetest_SM_Test.mq5",
  () => {
    const config: FourBrainConfig = {
      direction: { modules: ["ema"], timeframe: "M15" },
      setup: { modules: ["ema"], timeframe: "M5" },
      execution: { modules: ["ema"], timeframe: "M5" },
      management: {
        riskPercent: 1.0,
        rewardRisk: 2.0,
        stopBuffer: 20,
        breakEvenEnabled: true,
        breakEvenAtR: 1.0,
        maxOpenTrades: 3,
      },
    };
    const aiWiring: AiBrainWiring = {
      direction_brain: `void Direction_Brain_Execute() {
   int nb = EMASM_M15_Bias();
   if(nb != gBias && nb != 0) { gBias = nb; gSetupActive = false; }
}`,
      setup_brain: `void Setup_Brain_Execute() {
   EMASM_M5_Tick(gBias);
   if(EMASM_M5_SetupActive()) { gSetupActive = true; gSetupDir = EMASM_M5_ActiveDir(); gSetupSLHint = EMASM_M5_ActiveSL(); }
   else { gSetupActive = false; }
}`,
      execution_brain: `void Execution_Brain_Execute() {
   EMASM_M5_Tick(gBias);
   if(EMASM_M5_JustConfirmed()) { gExecSignal = true; gExecDir = EMASM_M5_ConfirmDir(); gExecSL = EMASM_M5_ConfirmSL(); }
}`,
      required_sms: ["EMASM_M15", "EMASM_M5"],
      sm_configs: {
        ema_M5: {
          type: "ema",
          id: "M5",
          TF: "PERIOD_M5",
          tf: "M5",
          params: { fastPeriod: 12, slowPeriod: 48, retestPoints: 0, requireCross: true },
        },
      },
    };
    const code = generateEA({
      eaName: "EMA_CrossRetest_SM_Test",
      config,
      globalSymbol: "EURUSD",
      globalMagic: 990780,
      aiWiring,
    });
    const checks: Array<[string, boolean]> = [
      ["M15 bias SM embedded", code.includes("int EMASM_M15_Bias()")],
      ["M5 SM embedded", code.includes("void EMASM_M5_Tick(")],
      [
        "both SMs reset in OnInit",
        code.includes("EMASM_M15_Reset();") && code.includes("EMASM_M5_Reset();"),
      ],
      ["CROSSED gate present", code.includes("EMASM_M5_CROSSED") && code.includes("bullCross")],
      [
        "setup uses SetupActive",
        code.includes("EMASM_M5_SetupActive()") && code.includes("EMASM_M5_JustConfirmed()"),
      ],
      ["direction alignment gate", code.includes("disagrees with bias")],
    ];
    return { code, checks };
  },
);

// ── Template-mode EMA EA: confirm the MA helper is emitted AND used (drawn) ────
runAiTest("EMA cross (template, drawn MAs)", "EMA_Cross_Template_Test.mq5", () => {
  const config: FourBrainConfig = {
    direction: {
      modules: ["ema"],
      timeframe: "H1",
      parameters: { fastPeriod: 12, slowPeriod: 48 },
    },
    setup: { modules: ["ema"], timeframe: "M5", parameters: { fastPeriod: 12, slowPeriod: 48 } },
    execution: { modules: ["engulfing"], timeframe: "M5" },
    management: {
      riskPercent: 1.0,
      rewardRisk: 2.0,
      stopBuffer: 50,
      breakEvenEnabled: true,
      breakEvenAtR: 1.5,
      maxOpenTrades: 3,
    },
  } as FourBrainConfig;
  const code = generateEA({
    eaName: "EMA_Cross_Template_Test",
    config,
    globalSymbol: "EURUSD",
    globalMagic: 990779,
  });
  const checks: Array<[string, boolean]> = [
    ["B4_MA helper emitted", code.includes("int B4_MA(")],
    ["ChartIndicatorAdd present", code.includes("ChartIndicatorAdd(")],
    ["direction uses B4_MA", /B4_MA\(PERIOD_H1, \d+, MODE_EMA\)/.test(code)],
    ["setup uses B4_MA", /B4_MA\(PERIOD_M5, \d+, MODE_EMA\)/.test(code)],
    ["no fake summation EMA", !code.includes("fastSum")],
  ];
  return { code, checks };
});

// ── Template-mode MES EA: engulfing on ALL 3 brains uses the verified EGSM ─────
// Proves Phase 2B wiring: Direction/Setup/Execution brains call EGSM_*_ functions
// (NOT a simplified inline body-engulf), and the assembler embeds + ticks + resets
// one EGSM per brain timeframe.
runAiTest("MES engulfing (template, verified EGSM)", "MES_Engulfing_Template_Test.mq5", () => {
  const config: FourBrainConfig = {
    direction: { modules: ["engulfing"], timeframe: "D1" },
    setup: { modules: ["engulfing"], timeframe: "H4" },
    execution: { modules: ["engulfing"], timeframe: "M30" },
    management: {
      riskPercent: 1.0,
      rewardRisk: 2.0,
      stopBuffer: 30,
      maxOpenTrades: 1,
    },
  } as FourBrainConfig;
  const code = generateEA({
    eaName: "MES_Engulfing_Template_Test",
    config,
    globalSymbol: "XAUUSD",
    globalMagic: 770077,
  });
  const checks: Array<[string, boolean]> = [
    ["EGSM D1 embedded", code.includes("void EGSM_D1_Tick(")],
    ["EGSM H4 embedded", code.includes("void EGSM_H4_Tick(")],
    ["EGSM M30 embedded", code.includes("void EGSM_M30_Tick(")],
    ["direction uses EGSM confirm", code.includes("EGSM_D1_BullJustConfirmed()")],
    ["setup uses EGSM active zone", code.includes("EGSM_H4_HasActiveBull()")],
    ["setup SL hint from zone", code.includes("EGSM_H4_LatestBullLL()")],
    ["exec uses EGSM confirm+SL", code.includes("EGSM_M30_BullConfirmSL()")],
    ["EGSM ticked (D1)", code.includes("EGSM_D1_Tick(")],
    ["EGSM ticked (H4)", code.includes("EGSM_H4_Tick(")],
    ["EGSM ticked (M30)", code.includes("EGSM_M30_Tick(")],
    ["EGSM reset (D1)", code.includes("EGSM_D1_Reset();")],
    ["EGSM reset (H4)", code.includes("EGSM_H4_Reset();")],
    ["EGSM reset (M30)", code.includes("EGSM_M30_Reset();")],
    ["multi-candle detect present", code.includes("took %d candle(s)")],
    ["NO fake inline body-engulf", !code.includes("c1 >= o2 && o1 <= c2")],
    ["roadblock query emitted", code.includes("double EGSM_D1_RoadblockBull()")],
    ["path-clear query emitted", code.includes("bool EGSM_D1_PathClearBull()")],
  ];
  return { code, checks };
});

runAiTest("EMA test gates later iFVG", "EMA_Test_Then_IFVG_Test.mq5", () => {
  const config: FourBrainConfig = {
    direction: { modules: ["ema"], timeframe: "M5" },
    setup: { modules: ["ema", "fvg_inversion"], timeframe: "M5" },
    execution: { modules: ["fvg_inversion"], timeframe: "M5" },
    management: {
      riskPercent: 1,
      rewardRisk: 3,
      stopBuffer: 20,
      breakEvenEnabled: true,
      breakEvenAtR: 1.5,
      maxOpenTrades: 1,
      maxStopPoints: 70,
    },
  };
  const aiWiring: AiBrainWiring = {
    direction_brain: `int gEmaIfvgSeqBias_M5 = 0;
datetime gEmaIfvgCrossTime_M5 = 0;
datetime gEmaIfvgTestTime_M5 = 0;

void Direction_Brain_Execute() {
   static int _lastBias = 0;
   int hFast = B4_MA(PERIOD_M5, 12, MODE_EMA);
   int hSlow = B4_MA(PERIOD_M5, 48, MODE_EMA);
   datetime barTime = iTime(InpSymbol, PERIOD_M5, 1);
   double f1 = B4_MAval(hFast, 1), s1 = B4_MAval(hSlow, 1);
   double f2 = B4_MAval(hFast, 2), s2 = B4_MAval(hSlow, 2);
   bool bullCross = (f2 <= s2 && f1 > s1);
   bool bearCross = (f2 >= s2 && f1 < s1);
   if(bullCross) {
      gBias = 1; gEmaIfvgSeqBias_M5 = 1; gEmaIfvgCrossTime_M5 = barTime; gEmaIfvgTestTime_M5 = 0;
   } else if(bearCross) {
      gBias = -1; gEmaIfvgSeqBias_M5 = -1; gEmaIfvgCrossTime_M5 = barTime; gEmaIfvgTestTime_M5 = 0;
   }
   if(gBias != _lastBias) { _lastBias = gBias; gSetupActive = false; }
}`,
    setup_brain: `void Setup_Brain_Execute() {
   gSetupActive = false; gSetupDir = 0; gSetupSLHint = 0.0;
   datetime barTime = iTime(InpSymbol, PERIOD_M5, 1);
   if(gBias == 0) { gEmaIfvgSeqBias_M5 = 0; gEmaIfvgCrossTime_M5 = 0; gEmaIfvgTestTime_M5 = 0; return; }
   if(gBias != gEmaIfvgSeqBias_M5) return;
   int hFast = B4_MA(PERIOD_M5, 12, MODE_EMA);
   int hSlow = B4_MA(PERIOD_M5, 48, MODE_EMA);
   double fast = B4_MAval(hFast, 1), slow = B4_MAval(hSlow, 1);
   double hi = iHigh(InpSymbol, PERIOD_M5, 1), lo = iLow(InpSymbol, PERIOD_M5, 1);
   bool touchedFast = (lo <= fast && hi >= fast);
   bool touchedSlow = (lo <= slow && hi >= slow);
   if(gEmaIfvgTestTime_M5 == 0 && gEmaIfvgCrossTime_M5 > 0 && barTime > gEmaIfvgCrossTime_M5 && touchedSlow)
      gEmaIfvgTestTime_M5 = barTime;
   IFVGSM_M5_Tick(1);
   datetime invTime = (gBias == 1) ? IFVGSM_M5_BullInversionTime() : IFVGSM_M5_BearInversionTime();
   if(gEmaIfvgTestTime_M5 > 0 && invTime > gEmaIfvgTestTime_M5) { gSetupActive = true; gSetupDir = gBias; }
}`,
    execution_brain: `void Execution_Brain_Execute() {
   gExecSignal = false; gExecDir = 0; gExecSL = 0.0;
   IFVGSM_M5_Tick(1);
   datetime bullInv = IFVGSM_M5_BullInversionTime();
   datetime bearInv = IFVGSM_M5_BearInversionTime();
   if(gSetupActive && gSetupDir == 1 && gBias == 1 && IFVGSM_M5_BullJustInverted() && bullInv > gEmaIfvgTestTime_M5) {
      gExecSignal = true; gExecDir = 1; gExecSL = IFVGSM_M5_BullInversionSL();
   } else if(gSetupActive && gSetupDir == -1 && gBias == -1 && IFVGSM_M5_BearJustInverted() && bearInv > gEmaIfvgTestTime_M5) {
      gExecSignal = true; gExecDir = -1; gExecSL = IFVGSM_M5_BearInversionSL();
   }
}`,
    semantics: {
      version: 1,
      source: "deterministic_adapter",
      timeframe: "M5",
      modules: ["ema", "fvg_inversion"],
      direction: {
        module: "ema",
        event: "cross",
        fastPeriod: 12,
        slowPeriod: 48,
        resetPolicy: "opposite_cross",
      },
      setup: {
        gate: "ema_retest",
        target: "slow",
        targetLabel: "slow EMA (48)",
        mustOccurAfter: "direction_event",
      },
      execution: {
        module: "fvg_inversion",
        entryEvent: "formation",
        mustOccurAfter: "setup_gate",
      },
      assumptions: [],
    },
    validation: {
      status: "pass",
      errors: [],
      warnings: [],
    },
    sm_configs: {
      ifvg_M5: {
        type: "fvg_inversion",
        id: "M5",
        TF: "PERIOD_M5",
        tf: "M5",
        params: { expiryBars: 24 },
      },
    },
  };
  const code = generateEA({
    eaName: "EMA_Test_Then_IFVG_Test",
    config,
    globalSymbol: "EURUSD",
    globalMagic: 990781,
    aiWiring,
  });
  const checks: Array<[string, boolean]> = [
    ["IFVG time accessors emitted", code.includes("LatestBullInversionTime")],
    [
      "setup compares just-formed IFVG after EMA test",
      code.includes("invTime > gEmaIfvgTestTime_M5"),
    ],
    [
      "slow-only EMA retest gate is preserved",
      code.includes("&& touchedSlow") && !code.includes("touchedFast || touchedSlow"),
    ],
    ["execution uses iFVG formation signal", code.includes("BullJustInverted()")],
    [
      "execution rechecks bias/setup/time gate",
      code.includes("gBias == 1") && code.includes("bullInv > gEmaIfvgTestTime_M5"),
    ],
    ["execution uses formation SL", code.includes("BullInversionSL()")],
    ["uses just-closed bar tick", code.includes("IFVGSM_M5_Tick(1)")],
    ["AI audit header emitted", code.includes("AI validation: pass")],
    ["AI audit shows slow EMA target", code.includes("AI setup") && code.includes("slow EMA (48)")],
  ];
  return { code, checks };
});

// ── EG+EF (Engulfing / Engulfing Failed) as Setup→Execution via AI path ─────
runAiTest("EG+EF as Setup→Execution (MES)", "EG_EF_Setup_Exec_Test.mq5", () => {
  const config: FourBrainConfig = {
    direction: { modules: ["bos"], timeframe: "H4" },
    setup: { modules: ["engulfing"], timeframe: "H4" },
    execution: { modules: ["engulfing"], timeframe: "M30" },
    management: {
      riskPercent: 1.0,
      rewardRisk: 3.0,
      stopBuffer: 20,
      breakEvenEnabled: true,
      breakEvenAtR: 1.5,
      maxOpenTrades: 1,
    },
  };
  const aiWiring: AiBrainWiring = {
    direction_brain: `void Direction_Brain_Execute() {
  if(BOSSM_H4_BullBias()) { gBias = 1; }
  else if(BOSSM_H4_BearBias()) { gBias = -1; }
  else { gBias = 0; }
}`,
    setup_brain: `void Setup_Brain_Execute() {
  gSetupActive = false; gSetupDir = 0; gSetupSLHint = 0.0;
  if(gBias == 1 && EGSM_H4_HasActiveBull()) {
    gSetupActive = true; gSetupDir = 1; gSetupSLHint = EGSM_H4_LatestBullLL();
  } else if(gBias == -1 && EGSM_H4_HasActiveBear()) {
    gSetupActive = true; gSetupDir = -1; gSetupSLHint = EGSM_H4_LatestBearUL();
  }
}`,
    execution_brain: `void Execution_Brain_Execute() {
  gExecSignal = false; gExecDir = 0; gExecSL = 0.0;
  if(!gSetupActive) return;
  if(gSetupDir == 1 && EGSM_M30_BullJustConfirmed()) {
    gExecSignal = true; gExecDir = 1; gExecSL = EGSM_M30_BullConfirmSL();
  } else if(gSetupDir == -1 && EGSM_M30_BearJustConfirmed()) {
    gExecSignal = true; gExecDir = -1; gExecSL = EGSM_M30_BearConfirmSL();
  }
}`,
    required_sms: ["BOSSM_H4", "EGSM_H4", "EGSM_M30"],
    sm_configs: {
      bos_H4: {
        type: "bos",
        id: "H4",
        TF: "PERIOD_H4",
        tf: "H4",
        params: { swingLen: 5, lookback: 20 },
      },
      eg_H4: {
        type: "engulfing",
        id: "H4",
        TF: "PERIOD_H4",
        tf: "H4",
        params: { scanBack: 3, expiryBars: 200 },
      },
      eg_M30: {
        type: "engulfing",
        id: "M30",
        TF: "PERIOD_M30",
        tf: "M30",
        params: { scanBack: 3, expiryBars: 100 },
      },
    },
  };
  const code = generateEA({
    eaName: "EG_EF_Setup_Exec_Test",
    config,
    globalSymbol: "EURUSD",
    globalMagic: 990790,
    aiWiring,
  });
  const checks: Array<[string, boolean]> = [
    ["EGSM_H4 SM embedded", code.includes("EGSM_H4_Reset()")],
    ["EGSM_M30 SM embedded", code.includes("EGSM_M30_Reset()")],
    ["EG detection fn present", code.includes("EGSM_H4_Detect(")],
    ["EF flip logic present — BULL→BEAR", code.includes("BULL EG FAILED")],
    ["EF flip logic present — BEAR→BULL", code.includes("BEAR EG FAILED")],
    ["BullJustConfirmed accessor present", code.includes("EGSM_M30_BullJustConfirmed()")],
    ["BearJustConfirmed accessor present", code.includes("EGSM_M30_BearJustConfirmed()")],
    ["HasActiveBull setup gate", code.includes("EGSM_H4_HasActiveBull()")],
    ["LatestBullLL SL hint", code.includes("EGSM_H4_LatestBullLL()")],
    ["Assembler controls Tick — EGSM_H4_Tick(3)", code.includes("EGSM_H4_Tick(3)")],
    ["Assembler controls Tick — EGSM_M30_Tick(3)", code.includes("EGSM_M30_Tick(3)")],
  ];
  return { code, checks };
});

function runModuleContractAudit() {
  console.log(`\n── Module contract registry audit ──`);

  const checks: Array<[string, boolean, string?]> = [];
  const libraryIds = MODULE_LIBRARY.map((m) => m.id);
  const uiIds = Object.keys(MODULE_UI_PARAMS);
  const contractIds = Object.keys(MODULE_CONTRACTS);
  const knownIds = [...new Set([...libraryIds, ...uiIds])];

  const missingContracts = knownIds.filter((id) => !getModuleContract(id));
  checks.push([
    "every library/UI module has a contract",
    missingContracts.length === 0,
    missingContracts.join(", "),
  ]);

  const orphanContracts = contractIds.filter((id) => !knownIds.includes(id));
  checks.push([
    "contract ids are backed by library or UI vocabulary",
    orphanContracts.length === 0,
    orphanContracts.join(", "),
  ]);
  checks.push([
    "registered SM function is allowed",
    moduleContractAllowsSmFunction("IFVGSM", "IFVGSM_M5_BullJustInverted("),
  ]);
  checks.push([
    "invented SM function is rejected",
    !moduleContractAllowsSmFunction("IFVGSM", "IFVGSM_M5_DoMagicThing("),
  ]);

  for (const [id, contract] of Object.entries(MODULE_CONTRACTS)) {
    const eventless = contract.semanticEvents.length === 0;
    checks.push([`${id}: has semantic events`, !eventless]);

    const roleless = contract.supportedRoles.length === 0;
    checks.push([`${id}: has supported roles`, !roleless]);

    const eventsOutsideRoles = contract.semanticEvents.filter((event) =>
      event.roles.some((role) => !contract.supportedRoles.includes(role)),
    );
    checks.push([
      `${id}: event roles are supported`,
      eventsOutsideRoles.length === 0,
      eventsOutsideRoles.map((event) => event.id).join(", "),
    ]);

    const eventsWithoutQueries = contract.semanticEvents.filter(
      (event) => event.queryFunctions.length === 0,
    );
    checks.push([
      `${id}: events expose query functions`,
      eventsWithoutQueries.length === 0,
      eventsWithoutQueries.map((event) => event.id).join(", "),
    ]);

    if (contract.implementation === "state_machine") {
      checks.push([`${id}: state-machine prefix declared`, Boolean(contract.smPrefix)]);
      checks.push([`${id}: state-machine type declared`, Boolean(contract.smType)]);
      checks.push([`${id}: state-machine tick policy declared`, contract.tickArgPolicy !== "none"]);
    }
  }

  for (const [name, ok, detail] of checks) {
    console.log(`        ${ok ? "✓" : "✗"} ${name}${!ok && detail ? ` (${detail})` : ""}`);
  }
  if (checks.some(([, ok]) => !ok)) totalWarn++;
}

runModuleContractAudit();

console.log(`\n${items.length + 1} files emitted, ${totalWarn} static warning(s).`);
console.log(`Next: open verify/mql5/*.mq5 in MetaEditor and compile (F7).\n`);
