/**
 * Phase 0 policy checks — assembler detection and apply-fix gate rules.
 */
import {
  canApplyAiSurgicalFix,
  compileLogHasErrors,
  detectEaCodegenKind,
  isLegacyFlatRulesBlueprint,
  prefersBlueprintRegen,
} from "../src/lib/ea-generation-policy";
import type { StrategyBlueprint } from "../src/types/blueprint";
import { DEFAULT_BLUEPRINT } from "../src/types/blueprint";

function assertOk(condition: unknown, message: string): asserts condition {
  if (!condition) throw new Error(message);
}

function assertEq<T>(actual: T, expected: T, message: string) {
  if (actual !== expected) {
    throw new Error(`${message}: expected ${String(expected)}, got ${String(actual)}`);
  }
  console.log(`[OK  ] ${message}`);
}

const fourBrainBp: StrategyBlueprint = {
  ...DEFAULT_BLUEPRINT,
  fourBrain: {
    direction: { modules: ["bos"], timeframe: "H1" },
    execution: { modules: ["engulfing"], timeframe: "M5" },
    management: { riskPercent: 1, rewardRisk: 2, maxOpenTrades: 1 },
  },
};

const legacyBp: StrategyBlueprint = {
  ...DEFAULT_BLUEPRINT,
  rules: [{ id: "r1", type: "custom", description: "test", compilable: true }],
};

console.log("\nEA generation policy tests\n");

assertOk(isLegacyFlatRulesBlueprint(legacyBp), "legacy blueprint detected");
assertOk(!isLegacyFlatRulesBlueprint(fourBrainBp), "fourBrain not legacy");
console.log("[OK  ] legacy vs fourBrain classification");

const blueprintCode = "// Generated by EAbuilder2 — 4-Brain Architecture (blueprint SM)";
assertEq(detectEaCodegenKind(blueprintCode), "fourbrain_assembler", "blueprint SM tag");
assertOk(prefersBlueprintRegen(blueprintCode, fourBrainBp), "prefers regen for blueprint");
console.log("[OK  ] blueprint regen preference");

const flowCode = "void DetectStep_0() { RegisterEvent(0, 1, t, c, 0.0); }";
assertEq(detectEaCodegenKind(flowCode), "flow_engine", "flow engine tag");

const blocked = canApplyAiSurgicalFix(blueprintCode, fourBrainBp, null);
assertOk(!blocked.allowed, "blocks apply-fix without compile log");
assertOk(blocked.reason?.includes("verified assembler"), "blocked reason");
console.log("[OK  ] apply-fix blocked without compile errors");

const allowed = canApplyAiSurgicalFix(
  blueprintCode,
  fourBrainBp,
  "error: undeclared identifier 'Foo'",
);
assertOk(allowed.allowed, "allows apply-fix with compile errors");
console.log("[OK  ] apply-fix allowed with compile errors");

assertOk(compileLogHasErrors("error: 'x' undeclared"), "compile errors detected");
assertOk(!compileLogHasErrors("result: 0 errors"), "clean compile log");
console.log("[OK  ] compile log parsing");

console.log("\n7 ea generation policy check(s) passed.\n");
