/**
 * MQL5 emit + static-lint verification.
 *
 *   npx tsx scripts/verify-mql5.ts
 *
 * Emits every recently-built generator's output to verify/mql5/*.mq5 so they can
 * be dropped into MetaEditor, and runs a static lint pass for the MQL5 pitfalls
 * listed in CLAUDE.md (MQL4-isms, brace/paren balance, bare Ask/Bid, etc.).
 *
 * Static lint is NOT a compiler — a clean report means "no obvious red flags",
 * the real gate is still MetaEditor F7. But it catches the cheap mistakes.
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

// Standalone full-indicator generators (each returns a complete .mq5)
import { generateMissDetector }            from "../src/lib/smc-modules/miss-detector";
import { generateMissStateModule }         from "../src/lib/smc-modules/miss-state-module";
import { generateRssSrrDetector }          from "../src/lib/smc-modules/rss-srr-detector";
import { generateRssSrrStateModule }       from "../src/lib/smc-modules/rss-srr-state-module";
import { generateFvgLiquidityDetector }    from "../src/lib/smc-modules/fvg-liquidity-detector";
import { generateObLiquidityDetector }     from "../src/lib/smc-modules/ob-liquidity-detector";
import { generateBbLiquidityDetector }     from "../src/lib/smc-modules/bb-liquidity-detector";
import { generateObFvgDetector }           from "../src/lib/smc-modules/ob-fvg-detector";
import { generateUnicornDetector }         from "../src/lib/smc-modules/unicorn-detector";
import { generateRsiHiddenDivergenceDetector }    from "../src/lib/indicator-modules/rsi-hidden-divergence-detector";
import { generateRsiHiddenDivergenceStateModule } from "../src/lib/indicator-modules/rsi-hidden-divergence-state-module";

// Inline state-machine fragment generator
import { genRsiHdSM } from "../src/generators/gen-rsi-hd-sm";

// Full 4-brain assembler (AI path)
import { generateEA } from "../src/generators/gen-ea";
import type { FourBrainConfig, MQL5CodeGenParams } from "../src/types/blueprint";
import type { AiBrainWiring } from "../src/lib/api-client";

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT = resolve(__dirname, "..", "verify", "mql5");
mkdirSync(OUT, { recursive: true });

// ── Wrap the inline SM fragment in a minimal compilable test indicator ────────
function wrapInlineSM(name: string, fragment: string, resetCall: string, tickCall: string): string {
  return `//+------------------------------------------------------------------+
//| ${name} — inline-SM compile harness (generated by verify-mql5)  |
//+------------------------------------------------------------------+
#property strict
#property indicator_chart_window
#property indicator_plots 0

string InpSymbol = "EURUSD";   // the real EA supplies this as an input
${fragment}
int OnInit() { InpSymbol = _Symbol; ${resetCall} return INIT_SUCCEEDED; }
void OnDeinit(const int reason) {}
int OnCalculate(const int rates_total, const int prev_calculated,
                const datetime &time[], const double &open[],
                const double &high[], const double &low[],
                const double &close[], const long &tick_volume[],
                const long &volume[], const int &spread[])
{
   static datetime _last = 0;
   datetime _t = iTime(InpSymbol, PERIOD_CURRENT, 0);
   if(_t != _last) { _last = _t; ${tickCall} }
   return rates_total;
}
`;
}

interface Item { file: string; code: string }
const items: Item[] = [
  { file: "Miss_Detector.mq5",                     code: generateMissDetector() },
  { file: "Miss_State_Module.mq5",                 code: generateMissStateModule() },
  { file: "RSS_SRR_Detector.mq5",                  code: generateRssSrrDetector() },
  { file: "RSS_SRR_State_Module.mq5",              code: generateRssSrrStateModule() },
  { file: "FVG_Liquidity_Detector.mq5",            code: generateFvgLiquidityDetector() },
  { file: "OB_Liquidity_Detector.mq5",             code: generateObLiquidityDetector() },
  { file: "BB_Liquidity_Detector.mq5",             code: generateBbLiquidityDetector() },
  { file: "OB_FVG_Detector.mq5",                   code: generateObFvgDetector() },
  { file: "Unicorn_Detector.mq5",                  code: generateUnicornDetector() },
  { file: "RSI_Hidden_Divergence_Detector.mq5",    code: generateRsiHiddenDivergenceDetector() },
  { file: "RSI_Hidden_Divergence_State_Module.mq5",code: generateRsiHiddenDivergenceStateModule() },
  { file: "_TEST_RSIHDSM_M15.mq5", code: wrapInlineSM(
      "RSIHDSM M15", genRsiHdSM("M15", "PERIOD_M15", "M15"),
      "RSIHDSM_M15_Reset();", "RSIHDSM_M15_Tick(50);") },
];

// ── Static lint ───────────────────────────────────────────────────────────────
function lint(code: string): string[] {
  const warn: string[] = [];
  const lines = code.split("\n");

  // brace / paren balance
  const count = (re: RegExp) => (code.match(re) ?? []).length;
  if (count(/\{/g) !== count(/\}/g)) warn.push(`brace imbalance: ${count(/\{/g)} { vs ${count(/\}/g)} }`);
  if (count(/\(/g) !== count(/\)/g)) warn.push(`paren imbalance: ${count(/\(/g)} ( vs ${count(/\)/g)} )`);

  // MQL4-isms / forbidden patterns (per CLAUDE.md)
  const pat: Array<[RegExp, string]> = [
    [/\b(Close|Open|High|Low|Time)\s*\[/g, "MQL4 series access (use iClose/iOpen/… )"],
    [/(?<![A-Za-z_.])(Ask|Bid)\b(?!\w)/g, "bare Ask/Bid (use SymbolInfoDouble SYMBOL_ASK/BID)"],
    [/\bSetMagicNumber\b/g, "SetMagicNumber (use trade.SetExpertMagicNumber)"],
    [/\bGetPointer\s*\(/g, "GetPointer on struct"],
  ];
  for (const [re, msg] of pat) {
    const hits: number[] = [];
    lines.forEach((ln, i) => { if (re.test(ln)) hits.push(i + 1); re.lastIndex = 0; });
    if (hits.length) warn.push(`${msg} @ lines ${hits.slice(0, 6).join(",")}${hits.length > 6 ? "…" : ""}`);
  }

  // struct defined inside a function (heuristic: 'struct' appearing after a non-zero brace depth)
  let depth = 0;
  lines.forEach((ln, i) => {
    const before = depth;
    depth += (ln.match(/\{/g) ?? []).length - (ln.match(/\}/g) ?? []).length;
    if (before > 0 && /^\s*struct\s+\w/.test(ln)) warn.push(`struct declared inside a block @ line ${i + 1}`);
  });

  return warn;
}

// ── Integration test: a full 4-brain EA using rsi_hd via the AI path ──────────
// sm_configs is EMPTY on purpose — reconcileStateMachines() must auto-embed
// RSIHDSM_M15 from the setup_brain reference, and OnInit must auto-call Reset.
function buildAiEa(): { code: string; checks: Array<[string, boolean]> } {
  const config: FourBrainConfig = {
    direction:  { modules: ["bos"],    timeframe: "H4" },
    setup:      { modules: ["rsi_hd"], timeframe: "M15" },
    execution:  { modules: ["fvg_inversion"], timeframe: "M5" },
    management: { riskPercent: 1.0, rewardRisk: 3.0, stopBuffer: 0.0005,
                  breakEvenEnabled: true, breakEvenAtR: 1.5, maxOpenTrades: 3 },
  };
  const aiWiring: AiBrainWiring = {
    direction_brain: `void Direction_Brain_Execute() { gBias = 1; }`,
    setup_brain: `void Setup_Brain_Execute() {
   RSIHDSM_M15_Tick(50);
   if(RSIHDSM_M15_BullJustConfirmed()) { gSetupActive = true; gSetupDir = 1; gSetupSLHint = RSIHDSM_M15_BullConfirmSL(); }
   else if(RSIHDSM_M15_BearJustConfirmed()) { gSetupActive = true; gSetupDir = -1; gSetupSLHint = RSIHDSM_M15_BearConfirmSL(); }
}`,
    execution_brain: `void Execution_Brain_Execute() {
   if(gSetupActive) { gExecSignal = true; gExecDir = gSetupDir; gExecSL = gSetupSLHint; }
}`,
    required_sms: ["RSIHDSM_M15"],
    sm_configs: {},   // intentionally empty → must be reconciled
  };
  const params: MQL5CodeGenParams = {
    eaName: "RSI_HD_Continuation_Test", config,
    globalSymbol: "EURUSD", globalMagic: 990777, aiWiring,
  };
  const code = generateEA(params);
  const checks: Array<[string, boolean]> = [
    ["SM auto-embedded (reconcile)", code.includes("void RSIHDSM_M15_Tick")],
    ["SM Reset auto-called in OnInit", code.includes("RSIHDSM_M15_Reset();")],
    ["RSI handle present",            code.includes("iRSI(InpSymbol, PERIOD_M15")],
    ["setup brain wired",             code.includes("RSIHDSM_M15_BullJustConfirmed()")],
  ];
  return { code, checks };
}

let totalWarn = 0;
console.log(`\nEmitting ${items.length} files → ${OUT}\n`);
for (const it of items) {
  writeFileSync(resolve(OUT, it.file), it.code, "utf8");
  const w = lint(it.code);
  totalWarn += w.length;
  const tag = w.length === 0 ? "OK  " : "WARN";
  console.log(`[${tag}] ${it.file}  (${it.code.split("\n").length} lines)`);
  for (const m of w) console.log(`        • ${m}`);
}
// ── Run the AI-path integration test ──────────────────────────────────────────
console.log(`\n── AI-path integration: RSI HD as Setup Brain ──`);
try {
  const { code, checks } = buildAiEa();
  writeFileSync(resolve(OUT, "RSI_HD_Continuation_Test.mq5"), code, "utf8");
  const lw = lint(code);
  console.log(`[${lw.length ? "WARN" : "OK  "}] RSI_HD_Continuation_Test.mq5  (${code.split("\n").length} lines)`);
  for (const m of lw) console.log(`        • ${m}`);
  totalWarn += lw.length;
  for (const [name, ok] of checks) console.log(`        ${ok ? "✓" : "✗"} ${name}`);
  if (checks.some(([, ok]) => !ok)) totalWarn++;
} catch (e) {
  console.log(`[FAIL] assembler threw: ${(e as Error).message}`);
  totalWarn++;
}

console.log(`\n${items.length + 1} files emitted, ${totalWarn} static warning(s).`);
console.log(`Next: open verify/mql5/*.mq5 in MetaEditor and compile (F7).\n`);
